// src/lib/countries.js
export const countries = [
  { name: "India", code: "+91", flag: "https://flagcdn.com/16x12/in.png" },
  { name: "United States", code: "+1", flag: "https://flagcdn.com/16x12/us.png" },
  { name: "United Kingdom", code: "+44", flag: "https://flagcdn.com/16x12/gb.png" },
  { name: "Canada", code: "+1", flag: "https://flagcdn.com/16x12/ca.png" },
  { name: "Australia", code: "+61", flag: "https://flagcdn.com/16x12/au.png" },
  { name: "Germany", code: "+49", flag: "https://flagcdn.com/16x12/de.png" },
  { name: "Afghanistan", code: "+93", flag: "https://flagcdn.com/16x12/af.png" },
  { name: "Albania", code: "+355", flag: "https://flagcdn.com/16x12/al.png" },
  { name: "Algeria", code: "+213", flag: "https://flagcdn.com/16x12/dz.png" },
  { name: "American Samoa", code: "+1-684", flag: "https://flagcdn.com/16x12/as.png" },
  { name: "Andorra", code: "+376", flag: "https://flagcdn.com/16x12/ad.png" },
  { name: "Angola", code: "+244", flag: "https://flagcdn.com/16x12/ao.png" },
  { name: "Anguilla", code: "+1-264", flag: "https://flagcdn.com/16x12/ai.png" },
  { name: "Antigua and Barbuda", code: "+1-268", flag: "https://flagcdn.com/16x12/ag.png" },
  { name: "Argentina", code: "+54", flag: "https://flagcdn.com/16x12/ar.png" },
  { name: "Armenia", code: "+374", flag: "https://flagcdn.com/16x12/am.png" },
  { name: "Aruba", code: "+297", flag: "https://flagcdn.com/16x12/aw.png" },
  { name: "Australia", code: "+61", flag: "https://flagcdn.com/16x12/au.png" },
  { name: "Austria", code: "+43", flag: "https://flagcdn.com/16x12/at.png" },
  { name: "Azerbaijan", code: "+994", flag: "https://flagcdn.com/16x12/az.png" },
  { name: "Bahamas", code: "+1-242", flag: "https://flagcdn.com/16x12/bs.png" },
  { name: "Bahrain", code: "+973", flag: "https://flagcdn.com/16x12/bh.png" },
  { name: "Bangladesh", code: "+880", flag: "https://flagcdn.com/16x12/bd.png" },
  { name: "Barbados", code: "+1-246", flag: "https://flagcdn.com/16x12/bb.png" },
  { name: "Belarus", code: "+375", flag: "https://flagcdn.com/16x12/by.png" },
  { name: "Belgium", code: "+32", flag: "https://flagcdn.com/16x12/be.png" },
  { name: "Belize", code: "+501", flag: "https://flagcdn.com/16x12/bz.png" },
  { name: "Benin", code: "+229", flag: "https://flagcdn.com/16x12/bj.png" },
  { name: "Bermuda", code: "+1-441", flag: "https://flagcdn.com/16x12/bm.png" },
  { name: "Bhutan", code: "+975", flag: "https://flagcdn.com/16x12/bt.png" },
  { name: "Bolivia", code: "+591", flag: "https://flagcdn.com/16x12/bo.png" },
  { name: "Bosnia and Herzegovina", code: "+387", flag: "https://flagcdn.com/16x12/ba.png" },
  { name: "Botswana", code: "+267", flag: "https://flagcdn.com/16x12/bw.png" },
  { name: "Brazil", code: "+55", flag: "https://flagcdn.com/16x12/br.png" },
  { name: "Brunei", code: "+673", flag: "https://flagcdn.com/16x12/bn.png" },
  { name: "Bulgaria", code: "+359", flag: "https://flagcdn.com/16x12/bg.png" },
  { name: "Burkina Faso", code: "+226", flag: "https://flagcdn.com/16x12/bf.png" },
  { name: "Burundi", code: "+257", flag: "https://flagcdn.com/16x12/bi.png" },
  { name: "Cambodia", code: "+855", flag: "https://flagcdn.com/16x12/kh.png" },
  { name: "Cameroon", code: "+237", flag: "https://flagcdn.com/16x12/cm.png" },
  { name: "Canada", code: "+1", flag: "https://flagcdn.com/16x12/ca.png" },
  { name: "Cape Verde", code: "+238", flag: "https://flagcdn.com/16x12/cv.png" },
  { name: "Cayman Islands", code: "+1-345", flag: "https://flagcdn.com/16x12/ky.png" },
  { name: "Central African Republic", code: "+236", flag: "https://flagcdn.com/16x12/cf.png" },
  { name: "Chad", code: "+235", flag: "https://flagcdn.com/16x12/td.png" },
  { name: "Chile", code: "+56", flag: "https://flagcdn.com/16x12/cl.png" },
  { name: "China", code: "+86", flag: "https://flagcdn.com/16x12/cn.png" },
  { name: "Colombia", code: "+57", flag: "https://flagcdn.com/16x12/co.png" },
  { name: "Comoros", code: "+269", flag: "https://flagcdn.com/16x12/km.png" },
  { name: "Congo", code: "+242", flag: "https://flagcdn.com/16x12/cg.png" },
  { name: "Costa Rica", code: "+506", flag: "https://flagcdn.com/16x12/cr.png" },
  { name: "Croatia", code: "+385", flag: "https://flagcdn.com/16x12/hr.png" },
  { name: "Cuba", code: "+53", flag: "https://flagcdn.com/16x12/cu.png" },
  { name: "Cyprus", code: "+357", flag: "https://flagcdn.com/16x12/cy.png" },
  { name: "Czech Republic", code: "+420", flag: "https://flagcdn.com/16x12/cz.png" },
  { name: "Denmark", code: "+45", flag: "https://flagcdn.com/16x12/dk.png" },
  { name: "Djibouti", code: "+253", flag: "https://flagcdn.com/16x12/dj.png" },
  { name: "Dominica", code: "+1-767", flag: "https://flagcdn.com/16x12/dm.png" },
  { name: "Dominican Republic", code: "+1-809", flag: "https://flagcdn.com/16x12/do.png" },
  { name: "Ecuador", code: "+593", flag: "https://flagcdn.com/16x12/ec.png" },
  { name: "Egypt", code: "+20", flag: "https://flagcdn.com/16x12/eg.png" },
  { name: "El Salvador", code: "+503", flag: "https://flagcdn.com/16x12/sv.png" },
  { name: "Equatorial Guinea", code: "+240", flag: "https://flagcdn.com/16x12/gq.png" },
  { name: "Eritrea", code: "+291", flag: "https://flagcdn.com/16x12/er.png" },
  { name: "Estonia", code: "+372", flag: "https://flagcdn.com/16x12/ee.png" },
  { name: "Eswatini", code: "+268", flag: "https://flagcdn.com/16x12/sz.png" },
  { name: "Ethiopia", code: "+251", flag: "https://flagcdn.com/16x12/et.png" },
  { name: "Fiji", code: "+679", flag: "https://flagcdn.com/16x12/fj.png" },
  { name: "Finland", code: "+358", flag: "https://flagcdn.com/16x12/fi.png" },
  { name: "France", code: "+33", flag: "https://flagcdn.com/16x12/fr.png" },
  { name: "Gabon", code: "+241", flag: "https://flagcdn.com/16x12/ga.png" },
  { name: "Gambia", code: "+220", flag: "https://flagcdn.com/16x12/gm.png" },
  { name: "Georgia", code: "+995", flag: "https://flagcdn.com/16x12/ge.png" },
  { name: "Germany", code: "+49", flag: "https://flagcdn.com/16x12/de.png" },
  { name: "Ghana", code: "+233", flag: "https://flagcdn.com/16x12/gh.png" },
  { name: "Gibraltar", code: "+350", flag: "https://flagcdn.com/16x12/gi.png" },
  { name: "Greece", code: "+30", flag: "https://flagcdn.com/16x12/gr.png" },
  { name: "Greenland", code: "+299", flag: "https://flagcdn.com/16x12/gl.png" },
  { name: "Grenada", code: "+1-473", flag: "https://flagcdn.com/16x12/gd.png" },
  { name: "Guadeloupe", code: "+590", flag: "https://flagcdn.com/16x12/gp.png" },
  { name: "Guam", code: "+1-671", flag: "https://flagcdn.com/16x12/gu.png" },
  { name: "Guatemala", code: "+502", flag: "https://flagcdn.com/16x12/gt.png" },
  { name: "Guernsey", code: "+44", flag: "https://flagcdn.com/16x12/gg.png" },
  { name: "Guinea", code: "+224", flag: "https://flagcdn.com/16x12/gn.png" },
  { name: "Guinea-Bissau", code: "+245", flag: "https://flagcdn.com/16x12/gw.png" },
  { name: "Guyana", code: "+592", flag: "https://flagcdn.com/16x12/gy.png" },
  { name: "Haiti", code: "+509", flag: "https://flagcdn.com/16x12/ht.png" },
  { name: "Honduras", code: "+504", flag: "https://flagcdn.com/16x12/hn.png" },
  { name: "Hong Kong", code: "+852", flag: "https://flagcdn.com/16x12/hk.png" },
  { name: "Hungary", code: "+36", flag: "https://flagcdn.com/16x12/hu.png" },
  { name: "Iceland", code: "+354", flag: "https://flagcdn.com/16x12/is.png" },
  { name: "India", code: "+91", flag: "https://flagcdn.com/16x12/in.png" },
  { name: "Indonesia", code: "+62", flag: "https://flagcdn.com/16x12/id.png" },
  { name: "Iran", code: "+98", flag: "https://flagcdn.com/16x12/ir.png" },
  { name: "Iraq", code: "+964", flag: "https://flagcdn.com/16x12/iq.png" },
  { name: "Ireland", code: "+353", flag: "https://flagcdn.com/16x12/ie.png" },
  { name: "Isle of Man", code: "+44", flag: "https://flagcdn.com/16x12/im.png" },
  { name: "Israel", code: "+972", flag: "https://flagcdn.com/16x12/il.png" },
  { name: "Italy", code: "+39", flag: "https://flagcdn.com/16x12/it.png" },
  { name: "Jamaica", code: "+1-876", flag: "https://flagcdn.com/16x12/jm.png" },
  { name: "Japan", code: "+81", flag: "https://flagcdn.com/16x12/jp.png" },
  { name: "Jersey", code: "+44", flag: "https://flagcdn.com/16x12/je.png" },
  { name: "Jordan", code: "+962", flag: "https://flagcdn.com/16x12/jo.png" },
  { name: "Kazakhstan", code: "+7", flag: "https://flagcdn.com/16x12/kz.png" },
  { name: "Kenya", code: "+254", flag: "https://flagcdn.com/16x12/ke.png" },
  { name: "Kiribati", code: "+686", flag: "https://flagcdn.com/16x12/ki.png" },
  { name: "Kuwait", code: "+965", flag: "https://flagcdn.com/16x12/kw.png" },
  { name: "Kyrgyzstan", code: "+996", flag: "https://flagcdn.com/16x12/kg.png" },
  { name: "Laos", code: "+856", flag: "https://flagcdn.com/16x12/la.png" },
  { name: "Latvia", code: "+371", flag: "https://flagcdn.com/16x12/lv.png" },
  { name: "Lebanon", code: "+961", flag: "https://flagcdn.com/16x12/lb.png" },
  { name: "Lesotho", code: "+266", flag: "https://flagcdn.com/16x12/ls.png" },
  { name: "Liberia", code: "+231", flag: "https://flagcdn.com/16x12/lr.png" },
  { name: "Libya", code: "+218", flag: "https://flagcdn.com/16x12/ly.png" },
  { name: "Liechtenstein", code: "+423", flag: "https://flagcdn.com/16x12/li.png" },
  { name: "Lithuania", code: "+370", flag: "https://flagcdn.com/16x12/lt.png" },
  { name: "Luxembourg", code: "+352", flag: "https://flagcdn.com/16x12/lu.png" },
  { name: "Macao", code: "+853", flag: "https://flagcdn.com/16x12/mo.png" },
  { name: "Madagascar", code: "+261", flag: "https://flagcdn.com/16x12/mg.png" },
  { name: "Malawi", code: "+265", flag: "https://flagcdn.com/16x12/mw.png" },
  { name: "Malaysia", code: "+60", flag: "https://flagcdn.com/16x12/my.png" },
  { name: "Maldives", code: "+960", flag: "https://flagcdn.com/16x12/mv.png" },
  { name: "Mali", code: "+223", flag: "https://flagcdn.com/16x12/ml.png" },
  { name: "Malta", code: "+356", flag: "https://flagcdn.com/16x12/mt.png" },
  { name: "Marshall Islands", code: "+692", flag: "https://flagcdn.com/16x12/mh.png" },
  { name: "Martinique", code: "+596", flag: "https://flagcdn.com/16x12/mq.png" },
  { name: "Mauritania", code: "+222", flag: "https://flagcdn.com/16x12/mr.png" },
  { name: "Mauritius", code: "+230", flag: "https://flagcdn.com/16x12/mu.png" },
  { name: "Mayotte", code: "+262", flag: "https://flagcdn.com/16x12/yt.png" },
  { name: "Mexico", code: "+52", flag: "https://flagcdn.com/16x12/mx.png" },
  { name: "Micronesia", code: "+691", flag: "https://flagcdn.com/16x12/fm.png" },
  { name: "Moldova", code: "+373", flag: "https://flagcdn.com/16x12/md.png" },
  { name: "Monaco", code: "+377", flag: "https://flagcdn.com/16x12/mc.png" },
  { name: "Mongolia", code: "+976", flag: "https://flagcdn.com/16x12/mn.png" },
  { name: "Montenegro", code: "+382", flag: "https://flagcdn.com/16x12/me.png" },
  { name: "Montserrat", code: "+1-664", flag: "https://flagcdn.com/16x12/ms.png" },
  { name: "Morocco", code: "+212", flag: "https://flagcdn.com/16x12/ma.png" },
  { name: "Mozambique", code: "+258", flag: "https://flagcdn.com/16x12/mz.png" },
  { name: "Myanmar", code: "+95", flag: "https://flagcdn.com/16x12/mm.png" },
  { name: "Namibia", code: "+264", flag: "https://flagcdn.com/16x12/na.png" },
  { name: "Nauru", code: "+674", flag: "https://flagcdn.com/16x12/nr.png" },
  { name: "Nepal", code: "+977", flag: "https://flagcdn.com/16x12/np.png" },
  { name: "Netherlands", code: "+31", flag: "https://flagcdn.com/16x12/nl.png" },
  { name: "New Caledonia", code: "+687", flag: "https://flagcdn.com/16x12/nc.png" },
  { name: "New Zealand", code: "+64", flag: "https://flagcdn.com/16x12/nz.png" },
  { name: "Nicaragua", code: "+505", flag: "https://flagcdn.com/16x12/ni.png" },
  { name: "Niger", code: "+227", flag: "https://flagcdn.com/16x12/ne.png" },
  { name: "Nigeria", code: "+234", flag: "https://flagcdn.com/16x12/ng.png" },
  { name: "Niue", code: "+683", flag: "https://flagcdn.com/16x12/nu.png" },
  { name: "Norfolk Island", code: "+672", flag: "https://flagcdn.com/16x12/nf.png" },
  { name: "North Korea", code: "+850", flag: "https://flagcdn.com/16x12/kp.png" },
  { name: "North Macedonia", code: "+389", flag: "https://flagcdn.com/16x12/mk.png" },
  { name: "Northern Mariana Islands", code: "+1-670", flag: "https://flagcdn.com/16x12/mp.png" },
  { name: "Norway", code: "+47", flag: "https://flagcdn.com/16x12/no.png" },
  { name: "Oman", code: "+968", flag: "https://flagcdn.com/16x12/om.png" },
  { name: "Pakistan", code: "+92", flag: "https://flagcdn.com/16x12/pk.png" },
  { name: "Palau", code: "+680", flag: "https://flagcdn.com/16x12/pw.png" },
  { name: "Palestine", code: "+970", flag: "https://flagcdn.com/16x12/ps.png" },
  { name: "Panama", code: "+507", flag: "https://flagcdn.com/16x12/pa.png" },
  { name: "Papua New Guinea", code: "+675", flag: "https://flagcdn.com/16x12/pg.png" },
  { name: "Paraguay", code: "+595", flag: "https://flagcdn.com/16x12/py.png" },
  { name: "Peru", code: "+51", flag: "https://flagcdn.com/16x12/pe.png" },
  { name: "Philippines", code: "+63", flag: "https://flagcdn.com/16x12/ph.png" },
  { name: "Poland", code: "+48", flag: "https://flagcdn.com/16x12/pl.png" },
  { name: "Portugal", code: "+351", flag: "https://flagcdn.com/16x12/pt.png" },
  { name: "Puerto Rico", code: "+1-787", flag: "https://flagcdn.com/16x12/pr.png" },
  { name: "Qatar", code: "+974", flag: "https://flagcdn.com/16x12/qa.png" },
  { name: "Réunion", code: "+262", flag: "https://flagcdn.com/16x12/re.png" },
  { name: "Romania", code: "+40", flag: "https://flagcdn.com/16x12/ro.png" },
  { name: "Russia", code: "+7", flag: "https://flagcdn.com/16x12/ru.png" },
  { name: "Rwanda", code: "+250", flag: "https://flagcdn.com/16x12/rw.png" },
  { name: "Saint Barthélemy", code: "+590", flag: "https://flagcdn.com/16x12/bl.png" },
  { name: "Saint Helena", code: "+290", flag: "https://flagcdn.com/16x12/sh.png" },
  { name: "Saint Kitts and Nevis", code: "+1-869", flag: "https://flagcdn.com/16x12/kn.png" },
  { name: "Saint Lucia", code: "+1-758", flag: "https://flagcdn.com/16x12/lc.png" },
  { name: "Saint Martin", code: "+590", flag: "https://flagcdn.com/16x12/mf.png" },
  { name: "Saint Pierre and Miquelon", code: "+508", flag: "https://flagcdn.com/16x12/pm.png" },
  { name: "Saint Vincent and the Grenadines", code: "+1-784", flag: "https://flagcdn.com/16x12/vc.png" },
  { name: "Samoa", code: "+685", flag: "https://flagcdn.com/16x12/ws.png" },
  { name: "San Marino", code: "+378", flag: "https://flagcdn.com/16x12/sm.png" },
  { name: "Sao Tome and Principe", code: "+239", flag: "https://flagcdn.com/16x12/st.png" },
  { name: "Saudi Arabia", code: "+966", flag: "https://flagcdn.com/16x12/sa.png" },
  { name: "Senegal", code: "+221", flag: "https://flagcdn.com/16x12/sn.png" },
  { name: "Serbia", code: "+381", flag: "https://flagcdn.com/16x12/rs.png" },
  { name: "Seychelles", code: "+248", flag: "https://flagcdn.com/16x12/sc.png" },
  { name: "Sierra Leone", code: "+232", flag: "https://flagcdn.com/16x12/sl.png" },
  { name: "Singapore", code: "+65", flag: "https://flagcdn.com/16x12/sg.png" },
  { name: "Sint Maarten", code: "+1-721", flag: "https://flagcdn.com/16x12/sx.png" },
  { name: "Slovakia", code: "+421", flag: "https://flagcdn.com/16x12/sk.png" },
  { name: "Slovenia", code: "+386", flag: "https://flagcdn.com/16x12/si.png" },
  { name: "Solomon Islands", code: "+677", flag: "https://flagcdn.com/16x12/sb.png" },
  { name: "Somalia", code: "+252", flag: "https://flagcdn.com/16x12/so.png" },
  { name: "South Africa", code: "+27", flag: "https://flagcdn.com/16x12/za.png" },
  { name: "South Korea", code: "+82", flag: "https://flagcdn.com/16x12/kr.png" },
  { name: "South Sudan", code: "+211", flag: "https://flagcdn.com/16x12/ss.png" },
  { name: "Spain", code: "+34", flag: "https://flagcdn.com/16x12/es.png" },
  { name: "Sri Lanka", code: "+94", flag: "https://flagcdn.com/16x12/lk.png" },
  { name: "Sudan", code: "+249", flag: "https://flagcdn.com/16x12/sd.png" },
  { name: "Suriname", code: "+597", flag: "https://flagcdn.com/16x12/sr.png" },
  { name: "Sweden", code: "+46", flag: "https://flagcdn.com/16x12/se.png" },
  { name: "Switzerland", code: "+41", flag: "https://flagcdn.com/16x12/ch.png" },
  { name: "Syria", code: "+963", flag: "https://flagcdn.com/16x12/sy.png" },
  { name: "Taiwan", code: "+886", flag: "https://flagcdn.com/16x12/tw.png" },
  { name: "Tajikistan", code: "+992", flag: "https://flagcdn.com/16x12/tj.png" },
  { name: "Tanzania", code: "+255", flag: "https://flagcdn.com/16x12/tz.png" },
  { name: "Thailand", code: "+66", flag: "https://flagcdn.com/16x12/th.png" },
  { name: "Timor-Leste", code: "+670", flag: "https://flagcdn.com/16x12/tl.png" },
  { name: "Togo", code: "+228", flag: "https://flagcdn.com/16x12/tg.png" },
  { name: "Tokelau", code: "+690", flag: "https://flagcdn.com/16x12/tk.png" },
  { name: "Tonga", code: "+676", flag: "https://flagcdn.com/16x12/to.png" },
  { name: "Trinidad and Tobago", code: "+1-868", flag: "https://flagcdn.com/16x12/tt.png" },
  { name: "Tunisia", code: "+216", flag: "https://flagcdn.com/16x12/tn.png" },
  { name: "Turkey", code: "+90", flag: "https://flagcdn.com/16x12/tr.png" },
  { name: "Turkmenistan", code: "+993", flag: "https://flagcdn.com/16x12/tm.png" },
  { name: "Turks and Caicos Islands", code: "+1-649", flag: "https://flagcdn.com/16x12/tc.png" },
  { name: "Tuvalu", code: "+688", flag: "https://flagcdn.com/16x12/tv.png" },
  { name: "Uganda", code: "+256", flag: "https://flagcdn.com/16x12/ug.png" },
  { name: "Ukraine", code: "+380", flag: "https://flagcdn.com/16x12/ua.png" },
  { name: "United Arab Emirates", code: "+971", flag: "https://flagcdn.com/16x12/ae.png" },
  { name: "United Kingdom", code: "+44", flag: "https://flagcdn.com/16x12/gb.png" },
  { name: "United States", code: "+1", flag: "https://flagcdn.com/16x12/us.png" },
  { name: "Uruguay", code: "+598", flag: "https://flagcdn.com/16x12/uy.png" },
  { name: "Uzbekistan", code: "+998", flag: "https://flagcdn.com/16x12/uz.png" },
  { name: "Vanuatu", code: "+678", flag: "https://flagcdn.com/16x12/vu.png" },
  { name: "Vatican City", code: "+39-06", flag: "https://flagcdn.com/16x12/va.png" },
  { name: "Venezuela", code: "+58", flag: "https://flagcdn.com/16x12/ve.png" },
  { name: "Vietnam", code: "+84", flag: "https://flagcdn.com/16x12/vn.png" },
  { name: "Virgin Islands (UK)", code: "+1-284", flag: "https://flagcdn.com/16x12/vg.png" },
  { name: "Virgin Islands (US)", code: "+1-340", flag: "https://flagcdn.com/16x12/vi.png" },
  { name: "Wallis and Futuna", code: "+681", flag: "https://flagcdn.com/16x12/wf.png" },
  { name: "Yemen", code: "+967", flag: "https://flagcdn.com/16x12/ye.png" },
  { name: "Zambia", code: "+260", flag: "https://flagcdn.com/16x12/zm.png" },
  { name: "Zimbabwe", code: "+263", flag: "https://flagcdn.com/16x12/zw.png" }


];